function introduction()

% Get screen size
screenSize = get(0, 'ScreenSize');

% Create the figure window
Fig = figure('Name', 'Non-inverting Operational Amplifier', ...
    'Units', 'pixels', ...  
    'Position', [0, 0, screenSize(3), screenSize(4)], ...  
    'NumberTitle', 'off', ... 
    'ToolBar', 'none', ... 
    'color', [0.8, 0.8, 0.8]); 

% Reading the image
x = imread('AON.jpg');  

% Image enlargement
scale_factor = 2;  
x_resized = imresize(x, scale_factor);  

% Get the resized image dimensions
[rows, cols, ~] = size(x_resized);

% We calculate the position to place the image on the left side of the screen, in the middle
posX = 0;  
posY = (screenSize(4) - rows) / 4;  

% Display the resized image in a window
imshow(x_resized);  

% Add title with Times New Roman font and size 12
title('Non-inverting Operational Amplifier', 'FontName', 'Times New Roman', 'FontSize', 18);  

% Set axis boundaries to position the image
axis([0 cols 0 rows]);  
set(gca, 'Position', [posX / screenSize(3), posY / screenSize(4), cols / screenSize(3), rows / screenSize(4)]);  

% Remove axes to view the image without borders
axis off;

% Create the menu with a group of buttons
GroupMeniu = uibuttongroup('Visible', 'on', ...
    'BackgroundColor', [0.5, 0.5, 0.5], ...   
    'ForegroundColor', [1, 1, 1], ...  
    'Title', 'Meniu', ...   
    'FontSize', 18, ...                   
    'TitlePosition', 'lefttop', ...        
    'Position', [0.05 0.85 0.90 0.15], ...  
    'BorderType', 'none', ...              
    'BorderColor', 'black');              

% Create menu title text
textTitle = uicontrol('Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.45 0.60 0.1 0.45], ...  
    'BackgroundColor', [1 1 1], ... 
    'ForegroundColor', 'black', ...      
    'String', 'Introduction', ...                
    'FontName', 'Times New Roman', ...
    'FontSize', 20, ...
    'Parent', GroupMeniu);          

% Creating the Chapter List
chapterList = uicontrol('Style', 'popupmenu', ...
    'String', {'Introduction', 'I/O Graphs', 'Av/Ri Graphs'}, ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.25 0.8 0.1 0.25], ...  
    'Callback', @(src, event) selectChapter(src), ...
    'Parent', GroupMeniu); 

% Callback function for selecting chapters
function selectChapter(src)
    selectedChapter = src.String{src.Value};
    
    switch selectedChapter
        case 'Introduction'
            disp('Navigation to the Introduction chapter');
            introduction();  
        case 'I/O Graphs'
            disp('Navigation to the I/O Graphs');
            Noninverting();   
        case 'Av/Ri Graphs'
            disp('Navigation to the Av/Ri Graphs');
            Gain();
    end
end

% Home button
homeButton = uicontrol('Style', 'pushbutton', ...
    'String', 'Home', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.35 0.6 0.1 0.4], ...   
    'Callback', @(src, event) goBackHome(), ...
    'Parent', GroupMeniu);

function goBackHome()
    close(Fig);  
    introduction(); 
end

% "<" button 
backButton = uicontrol('Style', 'pushbutton', ...
    'String', '<', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.15 0.6 0.1 0.4], ...   
    'Callback', @(src, event) goBackGain(), ...   
    'Parent', GroupMeniu);

% GoBack function to close the window and call win()
function goBackGain()
    close(Fig);  
    Gain();    
end
 

% "Close" button 
closeButton = uicontrol('Style', 'pushbutton', ...
    'String', 'Close', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.55 0.6 0.1 0.4], ...   
    'Callback', @(src, event) close(Fig), ...
    'Parent', GroupMeniu);  

% "Reset" button 
resetButton = uicontrol('Style', 'pushbutton', ...
    'String', 'Reset', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.65 0.6 0.1 0.4], ...   
    'Callback', @(src, event) resetIntroduction(), ...
    'Parent', GroupMeniu);  

% resetIntroducere function
    function resetIntroduction()
    close(Fig); % Close current window
    introduction(); % Call back the input function to reset it
end  

% ">" button 
nextButton = uicontrol('Style', 'pushbutton', ...
    'String', '>', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.75 0.6 0.1 0.4], ...   
    'Callback', @(src, event) goBackNoninverting(), ...
    'Parent', GroupMeniu);  

    function goBackNoninverting()
    close(Fig);  
    Noninverting();    
end

% Create a new group of buttons for Table of Contents
GroupTableOfContents = uibuttongroup('Visible', 'on', ...
    'BackgroundColor', [0.5, 0.5, 0.5], ...   
    'ForegroundColor', [1, 1, 1], ...  
    'Title', 'Cuprins', ...   
    'FontSize', 18, ...                    
    'TitlePosition', 'lefttop', ...        
    'Position', [0.55 0.07 0.37 0.70], ...  
    'BorderType', 'none', ...              
    'BorderColor', 'black');              

% "I/O Graphs" texts
graphsIOText = uicontrol('Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.60 0.81 0.2], ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'ForegroundColor', 'black', ...
    'String', 'In/Out Graphs', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'Parent', GroupTableOfContents);

% ">" button 
graphsIOButton = uicontrol('Style', 'pushbutton', ...
    'String', '>', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.86 0.60 0.1 0.2], ...
    'Callback', @(src, event) goBackNoninverting(), ...
    'Parent', GroupTableOfContents);    

% Text "Av/Ri Graphs"
graphsAVText = uicontrol('Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.05 0.35 0.81 0.2], ...
    'BackgroundColor', [0.8 0.8 0.8], ...
    'ForegroundColor', 'black', ...
    'String', 'Av/Ri Graphs', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'Parent', GroupTableOfContents);

% ">" button 
graphsAVButton = uicontrol('Style', 'pushbutton', ...
    'String', '>', ...
    'FontSize', 16, ...
    'FontName', 'Times New Roman', ...
    'ForegroundColor', [1, 1, 1], ...
    'BackgroundColor', [0.2, 0.2, 0.2], ...
    'Units', 'normalized', ...
    'Position', [0.86 0.35 0.1 0.2], ...
    'Callback', @(src, event) goBackGain(), ...
    'Parent', GroupTableOfContents);

end
